### ISSUE TITLE
variable reuse

### ISSUE THREAD

**Issue by chunkychode** [imkleats/neo4j-graphql-deepauth#7]
First awesome library exactly the silver bullet i needed 👍 
I found that you can not reuse variable names in all cases and not sure how to address it  

given this path 
```
@deepAuth(
  path :""" { OR:[
                  {personStarted_in: {Person:{id:"$userId"}}},
                  {personCreated:{Person:{id:"$userId"}}}
                ]
             }    
            
  """,
  variables: ["$userId"]`
```

produces the filter below which fails to produce results for personCreated_in 

```
"filter":{
	"OR": [
		{
			"personStarted_in": {
				"Person": {
					"id":"ABC"
				}
			},
			"personCreated_in": {
				"Person": {
					"id":"$userId"
				}
			},
		}
	]
}
```

of course if i modify the @deepAuth path to have 2 variables and supply them both in the context  then it works as expected.

**Comment by imkleats** [comment]
Thanks for checking it out, and I appreciate the issue. I'll take a look
today when I have a moment, but it sounds like I used `<string>.replace()`
instead of `replaceAll()`. Should be an easy fix.

Keep me posted on anything else you find too!

**Comment by imkleats** [comment]
Hey @chunkychode . I pushed a bugfix up under v0.2.2 that should address the Issue. If it doesn't resolve your problems, let me know and I'll reopen.
